{{- range $name, $src := .Values.datasource.strapi }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" $ }}-{{ $name }}-datasource-secrets
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: {{ $src.s3AccessKeyId | default $.Values.minio.rootUser | quote }}
  S3_SECRET_ACCESS_KEY: {{ $src.s3SecretAccessKey | default ($.Values.minio.password | required "minio.password is required") | quote }}
{{- end }}
