apiVersion: v1
kind: Secret
metadata:
  name: ragflow-postgres
type: Opaque
data:
  password: <Password>
---
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-midata-oauth
type: Opaque
data:
  clientId: <Client ID>
  clientSecret: <Client Secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-elasticsearch
type: Opaque
data:
  password: <Password>
---
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-minio
type: Opaque
data:
  password: <Password>
---
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-redis
type: Opaque
data:
  password: <Password>
---
apiVersion: v1
kind: Secret
metadata:
  name: ragflow-mcp
type: Opaque
data:
  apiKey: <API key>
