---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragflow.fullname" . }}-vision-prompts
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "overrides/prompts/*.md" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
