---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ragflow
  namespace: cosinus-ragflow
spec:
  interval: 5m0s
  url: https://github.com/scout-ch/tractor-k8s-shared-cosinus-ragflow
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ragflow
  namespace: cosinus-ragflow
spec:
  serviceAccountName: cosinus-ragflow
  interval: 10m0s
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: ragflow
  valuesFrom:
    - kind: Secret
      name: ragflow-midata-oauth
      valuesKey: clientId
      targetPath: ragflow.service_conf.oauth.midata.client_id
    - kind: Secret
      name: ragflow-midata-oauth
      valuesKey: clientSecret
      targetPath: ragflow.service_conf.oauth.midata.client_secret
    - kind: Secret
      name: ragflow-postgres
      valuesKey: password
      targetPath: ragflow.service_conf.postgres.password
    - kind: Secret
      name: ragflow-elasticsearch
      valuesKey: password
      targetPath: elasticsearch.password
    - kind: Secret
      name: ragflow-minio
      valuesKey: password
      targetPath: minio.password
    - kind: Secret
      name: ragflow-redis
      valuesKey: password
      targetPath: redis.password
    - kind: Secret
      name: ragflow-mcp
      valuesKey: apiKey
      targetPath: mcp.ragflowApiKey
  values:
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure # necessary, since we have multiple entrypoints
        cert-manager.io/cluster-issuer: letsencrypt
      host: rag.pfadi.ai
      tls:
        - hosts:
            - rag.pfadi.ai
            - mcp.rag.pfadi.ai
          secretName: tls-cert
    ragflow:
      service_conf:
        oauth:
          midata:
            issuer: https://pbs.puzzle.ch
            redirect_uri: https://rag.pfadi.ai/v1/user/oauth/callback/midata
        postgres:
          host: postgres.tractor.scout.ch
          name: cosinus-ragflow
          user: cosinus-ragflow
    mcp:
      enabled: true
      ingress:
        host: mcp.rag.pfadi.ai
    nodeSelector:
      kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pm8
