---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ragflow
  namespace: cosinus-ragflow
spec:
  interval: 5m0s
  url: https://github.com/scout-ch/tractor-k8s-shared-cosinus-ragflow
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ragflow
  namespace: cosinus-ragflow
spec:
  serviceAccountName: cosinus-ragflow
  interval: 10m0s
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: ragflow
  values:
    ingress:
      host: rag.pfadi.ai
    ragflow:
      service_conf:
        oauth:
          midata:
            issuer: https://pbs.puzzle.ch
            client_id:
              secret: ragflow-midata-oauth
              secretKey: clientId
            client_secret:
              secret: ragflow-midata-oauth
              secretKey: clientSecret
            redirect_uri: https://rag.pfadi.ai/v1/user/oauth/callback/midata
        postgres:
          host: postgres.tractor.scout.ch
          name: cosinus-ragflow
          user: cosinus-ragflow
          password:
            secret: ragflow-postgres
            secretKey: password
    elasticsearch:
      password:
        secret: ragflow-elasticsearch
        secretKey: password
    minio:
      password:
        secret: ragflow-minio
        secretKey: password
    redis:
      password:
        secret: ragflow-redis
        secretKey: password
    mcp:
      enabled: true
      ingress:
        host: mcp.rag.pfadi.ai
      ragflowApiKey:
        secret: ragflow-mcp
        secretKey: apiKey
    nodeSelector:
      kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pm8
