name: Test

on:
  push:
  pull_request:

jobs:
  datasource-adapter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        adapter: [strapi, cudesch, pdf]
    defaults:
      run:
        working-directory: ${{ matrix.adapter }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm test

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: azure/setup-helm@v4

      - run: helm lint ./helm -f helm/values.yaml -f helm/ci-dummy-secrets.yaml
